# Generated by Django 5.0.3 on 2024-03-12 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "embg",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinLengthValidator(16)],
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("birhdate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "game_name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "embg_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
            ],
        ),
    ]
