# Generated by Django 5.0.3 on 2024-05-13 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("ingredients", models.TextField(blank=True, null=True)),
                ("calories", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("capacity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SR", "Server"),
                            ("DE", "Delivery"),
                            ("MG", "Manager"),
                            ("CH", "Chef"),
                            ("DW", "DishWasher"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DishRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dish"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_the_week",
                    models.CharField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                            ("Sun", "Sunday"),
                        ],
                        max_length=4,
                    ),
                ),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.restaurant"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
